### ISSUE TITLE
Create dataset loader for OpenViVQA

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#270]
Dataloader name: `openvivqa/openvivqa.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?openvivqa

|     Dataset| openvivqa |
|-------------|---|
| Description | OpenViVQA (Open-domain Vietnamese Visual Question Answering) is a dataset for VQA (Visual Question Answering) with open-ended answers in Vietnamese. It consisted of 11199 images associated with 37914 question-answer pairs (QAs). Images in the OpenViVQA dataset are captured in Vietnam and question-answer pairs are created manually by Vietnamese crowd workers. |
| Subsets | - |
| Languages | vie |
| Tasks | Question Answering |
| License | MIT (mit) |
| Homepage | https://huggingface.co/datasets/uitnlp/OpenViVQA-dataset |
| HF URL | https://huggingface.co/datasets/uitnlp/OpenViVQA-dataset |
| Paper URL | https://doi.org/10.1016/j.inffus.2023.101868 |

**Comment by Gyyz** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
Hi @Gyyz, may we know the update on this dataloader issue? It's been 2 weeks since the last poke from the SEACrowd stale-checker, and we might consider unassigning if there's no progress update in the next 24 hours.

**Comment by Gyyz** [comment]
Hi, @Salsabil Maulana ***@***.***>, I am in China and on vocation, and have a bad network when connecting GitHub, I will update the repo when I get back to SG after Feb 18th. Thanks.

From: Salsabil Maulana Akbar ***@***.***>
Date: Friday, 2 February 2024 at 00:36
To: SEACrowd/seacrowd-datahub ***@***.***>
Cc: Yuze GAO ***@***.***>, Mention ***@***.***>
Subject: Re: [SEACrowd/seacrowd-datahub] Create dataset loader for OpenViVQA (Issue #270)

Hi @Gyyz<https://github.com/Gyyz>, may we know the update on this dataloader issue? It's been 2 weeks since the last poke from the SEACrowd stale-checker, and we might consider unassigning if there's no progress update in the next 24 hours.

**Comment by sabilmakbar** [comment]
okay then, I'll check it back after 18th Feb. In the meantime, pls take your time

**Comment by Gyyz** [comment]
Is there SeaCrowd features to load image? seem the images in the dataset are not from websites(like coco or flurk).
