### ISSUE TITLE
Create dataset loader for Thai-Lao Parallel Corpus

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#361]
Dataloader name: `tha_lao_embassy_parcor/tha_lao_embassy_parcor.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?tha_lao_embassy_parcor

|     Dataset| tha_lao_embassy_parcor |
|-------------|---|
| Description | Thai-Lao Parallel Corpus contains equivalent Thai and Lao sentence pairs derived from the website of the Royal Thai Embassy in Vientiane, Laos. |
| Subsets | - |
| Languages | tha, lao |
| Tasks | Machine Translation |
| License | Creative Commons Zero v1.0 Universal (cc0-1.0) |
| Homepage | https://github.com/PyThaiNLP/Thai-Lao-Parallel-Corpus/tree/master |
| HF URL | - |
| Paper URL | - |

**Comment by djanibekov** [comment]
#self-assign

**Comment by djanibekov** [comment]
The given home page url doesn't contain citation BibText. No description for .csv file names (.csv files are names almost same ".... .csv" ".... -sent.csv". To clarify these details I messaged author

**Comment by djanibekov** [comment]
1. thaiembassy-sent.csv is Thai-Lao Parallel sentence level and vientiane-thaiembassy.csv is Thai-Lao Parallel document level.  (implemented sent version since it is more suited for seq2s tasks)
2. exported BibTeX from [https://zenodo.org/records/5807093](https://www.linkedin.com/safety/go?url=https%3A%2F%2Fzenodo.org%2Frecords%2F5807093&trk=flagship-messaging-web&messageThreadUrn=urn%3Ali%3AmessagingThread%3A2-ZWE5MTZmZDMtYWNkYy00ZmVlLWJhYzAtMmFmNTYyMDg4OGVlXzAxMw%3D%3D).
