### ISSUE TITLE
Create dataset loader for CLIRMatrix

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#426]
Dataloader name: `clir_matrix/clir_matrix.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?clir_matrix

|     Dataset| clir_matrix |
|-------------|---|
| Description | CLIRMatrix is a massively large collection of bilingual and multilingual datasets for Cross-Lingual Information Retrieval extracted automatically from Wikipedia. CLIRMatrix comprises (1) BI-139, a bilingual dataset of queries in one language matched with relevant documents in another language for 139x138=19,182 language pairs, and (2) MULTI-8, a multilingual dataset of queries and documents jointly aligned in 8 different languages. |
| Subsets | - |
| Languages | tgl, ilo, min, jav, sun, ceb, vie, tha |
| Tasks | Text Retrieval |
| License | Unknown (unknown) |
| Homepage | https://github.com/ssun32/CLIRMatrix |
| HF URL | - |
| Paper URL | https://aclanthology.org/2020.emnlp-main.340/ |

**Comment by fhudi** [comment]
To whoever it may concern, in regards to the above [github-actions' reminder](https://github.com/SEACrowd/seacrowd-datahub/issues/426#issuecomment-1974189499),
I apologise for the delay and any inconveniences caused by this.
I am currently still working on this issue, please give some more time.
Regards.

**Comment by akhdanfadh** [comment]
@fhudi may we know if you are still working on this issue? It has already been one month since your last update.

**Comment by fhudi** [comment]
Hi @akhdanfadh, thanks for the reminder.

There are some files in the raw dataset that turned out to be empty file.
I was in the process of downloading the whole combination from the 9 languages supported,
to check and ask for clarification with the author, but somehow forgotten half-way.

---

Hi @ssun32,
I tried to create dataloader for your dataset but seems like there are empty files.
Could you please help checking the BI-139 for all queries in Indonesian (id)? 🙏 

![image](https://github.com/SEACrowd/seacrowd-datahub/assets/6541786/7261c78a-8834-4f71-8776-e11b16e8622a)

And also, regarding the license, it seems to be of `unknown` value,
but from your [CLIRMatrix site](https://www.cs.jhu.edu/~shuosun/clirmatrix/), it seems to be `cc-by-4.0` as written in the footnote.
So which one is correct? 🙏

**Comment by ssun32** [comment]
@fhudi It turns out there is zero overlap of the id-xx examples with the examples in the other language directions, probably due to incomplete Wikidata entries for ID when I created the dataset a few years ago. I recommend throwing away the language directions with empty files. Thanks for spotting the issue!

**Comment by holylovenia** [comment]
@fhudi Removed `ind` in both issue ticket and datasheet.

**Comment by fhudi** [comment]
@holylovenia @SamuelCahyawijaya 

---

The dataset's task is [TEXT_RETRIEVAL](https://github.com/SEACrowd/seacrowd-datahub/blob/master/seacrowd/utils/constants.py#L86), so the seacrowd schema for this dataset is [PAIRS](https://github.com/SEACrowd/seacrowd-datahub/blob/58514e04d994d7454e55221c8f01b8b1ae5c1d3c/seacrowd/utils/schemas/pairs.py#L7-L15) as noted in the [`constants.py`](https://github.com/SEACrowd/seacrowd-datahub/blob/58514e04d994d7454e55221c8f01b8b1ae5c1d3c/seacrowd/utils/constants.py#L245)

However, it seems the schema is incorrect, as it seems the triplet contains a continuous value for relevance score as defined follows:
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/6541786/3cc67e38-16b3-4a5e-bc1e-52dfd0d8b801)

Although [PAIRS_SCORE](https://github.com/SEACrowd/seacrowd-datahub/blob/58514e04d994d7454e55221c8f01b8b1ae5c1d3c/seacrowd/utils/constants.py#L313) seems to be more fitting, the dataset is formatted based on the _**task of IR (Information Retrieval)**_, where multiple document ids and it's relevance score in a single triplet.
Note that [PAIRS_MULTI](https://github.com/SEACrowd/seacrowd-datahub/blob/58514e04d994d7454e55221c8f01b8b1ae5c1d3c/seacrowd/utils/constants.py#L312) is categorical hence unfit.
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/6541786/c8849c0d-876e-4801-b4a0-f7e9f1bcefd9)

---

I think we are not going to support the format IR task, right?
Because if we do, there will be problematic to load the whole document text instead of IDs in the dataloader.

One of the immediate solution that I can think of, without much changes to the shared classes,
is letting the relevance score represented as categorical.

But WDYT?

**Comment by holylovenia** [comment]
Hi @fhudi, I agree with you. Let's do `source`-only for this dataloader. 👍
