### ISSUE TITLE
Create dataset loader for SREDFM

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [SEACrowd/seacrowd-datahub#48]
Dataloader name: `sredfm/sredfm.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?sredfm

|     Dataset| sredfm |
|-------------|---|
| Description | SREDFM is an automatically annotated dataset for relation extraction task covering 18 languages, 400 relation types, 13 entity types, totaling more than 40 million triplet instances. SREDFM includes Vietnamnese. |
| Subsets | SREDFM_vi |
| Languages | vie |
| Tasks | Relation Extraction |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/babelscape/rebel |
| HF URL | https://huggingface.co/datasets/Babelscape/SREDFM |
| Paper URL | https://aclanthology.org/2023.acl-long.237/ |

**Comment by sabilmakbar** [comment]
This is interesting, I'll take this first and see whether this can be done under a week, else I might release the task to others.

Btw, @SamuelCahyawijaya do we have a increasing bonus system after some time if the issue hasn't been picked up by anyone?

**Comment by sabilmakbar** [comment]
#self-assign

**Comment by sabilmakbar** [comment]
I'll take this once #62 has been reviewed. Will start it by next week.

**Comment by sabilmakbar** [comment]
Will try to get this done by EoW

**Comment by sabilmakbar** [comment]
Ugh, didn't have the chance to do this. will release this and see if anyone else can take this instead.

**Comment by khelli07** [comment]
#self-assign

**Comment by khelli07** [comment]
Hi, I did worked on this. The dataloader works, but apparently the test are hard to get passed, especially the seacrowd schema one. IIRC, I was having issues with IDs (duplicate). Currently have no time yet to fix it.

**Comment by khelli07** [comment]
Currently discussing it with @SamuelCahyawijaya

**Comment by khelli07** [comment]
Basically I got two problems
1) Spacing problem (the text and text offset asserted not equal. The content is the same, but the spacing is different)
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/71018093/39143115-3445-406f-bd22-dfe572c3636e)

2) Id uniqueness problem
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/71018093/3fd11112-6d43-4a30-b0b8-4dd758753a9d)

For second problem, I am still not sure why because:
- For source schema, I assume it only checks the `yielded id` (the `yield ..., { ... }` at the example loop)
- So for ID uniqueness, it is most likely coming from the seacrowd shema, BUT assuming that this is the ids the test check
"id": example["docid"], --> [skip the same doc id](https://github.com/khelli07/seacrowd-datahub/blob/add/sredfm/seacrowd/sea_datasets/sredfm/sredfm.py#L212)
"passages": passages, --> [use custom id (counter)](https://github.com/khelli07/seacrowd-datahub/blob/add/sredfm/seacrowd/sea_datasets/sredfm/sredfm.py#L212)
 "entities": entities, --> [counter](https://github.com/khelli07/seacrowd-datahub/blob/add/sredfm/seacrowd/sea_datasets/sredfm/sredfm.py#L270)
 "relations": relations, --> [counter](https://github.com/khelli07/seacrowd-datahub/blob/add/sredfm/seacrowd/sea_datasets/sredfm/sredfm.py#L212)
 
 Can look at the current full code [here](https://github.com/khelli07/seacrowd-datahub/blob/add/sredfm/seacrowd/sea_datasets/sredfm/sredfm.py)

**Comment by khelli07** [comment]
I think @SamuelCahyawijaya is currently busy. Might need another help.

**Comment by sabilmakbar** [comment]
For 1, I believe the text_offset was generated from the text field, but I saw on the offset text that a new line isn't present in the original text. Is it expected?

For 2, when I rechecked the schema, it checked the IDs defined on the example level to ensure they were unique. In your implementation, you're defining the entity & relation ID only by specifying an iteration counter, which leads to duplication on the check. Perhaps the workaround will be similar to what you did on the passage ID, appending it to some unique identifier for distinguishing entity ID and relation ID.

**Comment by khelli07** [comment]
OK, will take a look into this again in near time.

**Comment by khelli07** [comment]
For number 2) it is resolved now. I think I misunderstood the concept `id` at first.

Now, for problem number 1) -> yes, the problem is in the newline. Content-wise is the same

**Comment by khelli07** [comment]
![image](https://github.com/SEACrowd/seacrowd-datahub/assets/71018093/409233d2-862f-4308-b397-fe6e6d84f693)
omg, I passed the tests 😂 

The problem actually lies in the real dataset. The entities from the source datasets have "tidy" whitespaces (they don't have newlines). If you think about it, if the real passages are messy, the entity taken from it should also be messy. 

That being said, I suspect the source dataset does not actually take the entity from the passage cause the passage is a bit chaotic (in terms of whitespaces).

**Comment by holylovenia** [comment]
> ![image](https://private-user-images.githubusercontent.com/71018093/311443128-409233d2-862f-4308-b397-fe6e6d84f693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDM4NjQsIm5iZiI6MTcxMDE0MzU2NCwicGF0aCI6Ii83MTAxODA5My8zMTE0NDMxMjgtNDA5MjMzZDItODYyZi00MzA4LWIzOTctZmU2ZTZkODRmNjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA3NTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NDFhNGNhMjliODIzNjVlZDI4MmI4MzZmYzgwMzRmMDlhN2UwNTVhMzhmMWMyMDFmNGJmYTNmZDQwNDU0ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IIdvLMWyIbc2IsMzzvSjabKM94Ope7duXtzv6QMQGHY) omg, I passed the tests 😂
> 
> The problem actually lies in the real dataset. The entities from the source datasets have "tidy" whitespaces (they don't have newlines). If you think about it, if the real passages are messy, the entity taken from it should also be messy.
> 
> That being said, I suspect the source dataset does not actually take the entity from the passage cause the passage is a bit chaotic (in terms of whitespaces).

Awesome, hahaha. Glad to hear that you've resolved the issue! 👍
